artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  dataset_file_name: artifacts/data_ingestion/intent_classification.csv
  database_name: intent_classification
  collection_name: intents
  intents_file_name: artifacts/data_ingestion/intents.csv
  intent_column: predicted

data_validation:
  root_dir: artifacts/data_validation
  schema: columns
  dataset_file_name: artifacts/data_ingestion/intent_classification.csv
  validated_file_name: artifacts/data_validation/validated.csv

data_preprocessing:
  root_dir: artifacts/data_preprocessing
  dataset_file_name: artifacts/data_validation/validated.csv
  preprocessed_file_name: artifacts/data_preprocessing/preprocessed.csv
  named_entities: named_entities

data_transformation:
  root_dir: artifacts/data_transformation
  glove_url: http://nlp.stanford.edu/data/glove.6B.zip
  glove_zip_file: artifacts/data_transformation/glove/glove.6B.zip
  glove_dir: artifacts/data_transformation/glove
  glove_file: artifacts/data_transformation/glove/glove.6B.100d.txt
  dataset_file_name: artifacts/data_preprocessing/preprocessed.csv
  train_file: artifacts/data_transformation/train.csv
  test_file: artifacts/data_transformation/test.csv
  train_test_ratio: 0.8
  word2vec_model: artifacts/data_transformation/word2vec.model
  tfidf_vectorizer_path: artifacts/data_transformation/tfidf_vectorizer.pkl
  idf_scores_path: artifacts/data_transformation/idf_scores.pkl
  trained_word2vec_model_path: artifacts/data_transformation/trained_word2vec.model

model_trainer:
  root_dir: artifacts/model_trainer
  trained_model_file: artifacts/model_trainer/trained_model.pkl
  word2vec_model: artifacts/data_transformation/word2vec.model
  tfidf_vectorizer_path: artifacts/data_transformation/tfidf_vectorizer.pkl
  idf_scores_path: artifacts/data_transformation/idf_scores.pkl
  train_file: artifacts/data_transformation/train.csv
  test_file: artifacts/data_transformation/test.csv
  model_accuracy_baseline: 0.6

